#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
add_toc.py — يضيف "Table des matières" تلقائيا لكل ملفات part*.html
اللي ماعندهمش وحدة، فكل الدروس (chimie / physique / math).

الطريقة:
  1. كيدور على كل ملف content/<matiere>/lessons/<leçon>/model1/partN.html
  2. إلا كان فيه ديجا "Table des matières" -> يخطاه (skip)
  3. إلا ماكانش:
       - كيلقى كل <div class="section"> بلا id، وكيزيد ليها id="secN"
       - كيقرا العنوان ديال كل <h2> باش يبني لائحة الفهرس
       - كيدرج <div class="toc COLOR"> قبل أول section (بعد lesson-title/الوصف)
       - COLOR: chimie -> yellow | physique, math -> red
  4. كيزيد تنسيق CSS ديال .toc (مرة وحدة فقط) فـ assets/css/lesson-common.css

الاستعمال:
  python3 add_toc.py /storage/emulated/0/Web            # تنفيذ فعلي
  python3 add_toc.py /storage/emulated/0/Web --dry-run   # معاينة بلا تعديل
  python3 add_toc.py /storage/emulated/0/Web --no-backup # بلا نسخ احتياطية .bak

ملاحظة: كيدير نسخة احتياطية (filename.html.bak) لكل ملف قبل ما يبدلو،
        إلا كانت already موجودة ما كيبدلهاش (باش توصل ديما للنسخة الأصلية).
"""

import re
import sys
import argparse
from pathlib import Path

TOC_CSS = """
/* ====== Table des matières (auto-generated by add_toc.py) ====== */
.toc {
    border-radius: 10px;
    padding: 12px 16px;
    margin: 10px 0 18px;
    border-right: 4px solid #F4D03F;
    background: rgba(244, 208, 63, 0.06);
}
.toc.red {
    border-color: #FF6B6B;
    background: rgba(255, 107, 107, 0.06);
}
.toc.yellow {
    border-color: #F4D03F;
    background: rgba(244, 208, 63, 0.06);
}
.toc h3 {
    margin: 0 0 10px;
    font-size: 15px;
    display: flex;
    align-items: center;
    gap: 8px;
}
.toc ul {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 6px;
}
.toc li a {
    text-decoration: none;
    color: var(--text-primary, #e6edf3);
    font-size: 13.5px;
    display: flex;
    gap: 8px;
    align-items: flex-start;
    transition: color .15s;
}
.toc li a:hover {
    color: var(--accent-light, #4ECDC4);
}
.toc .num {
    font-weight: 700;
    color: var(--gold-text, #F4D03F);
    min-width: 18px;
}
/* ====== fin Table des matières ====== */
"""
TOC_CSS_MARKER = "/* ====== Table des matières (auto-generated by add_toc.py) ====== */"

SECTION_OPEN_RE = re.compile(r'<div class="section">')
SECTION_OPEN_WITH_ID_RE = re.compile(r'<div class="section" id="sec\d+">')
H2_RE = re.compile(r'<h2>\s*(?:<span class="num">\d+</span>\s*)?(.*?)\s*</h2>', re.S)
H1_RE = re.compile(r'<h1 class="lesson-title">.*?</h1>', re.S)
INTRO_P_RE = re.compile(r'(<h1 class="lesson-title">.*?</h1>\s*(?:<p[^>]*>.*?</p>\s*)?)', re.S)


def detect_color(path: Path) -> str:
    parts = {p.lower() for p in path.parts}
    if "chimie" in parts:
        return "yellow"
    if "physique" in parts or "math" in parts:
        return "red"
    return "yellow"  # valeur par défaut


def build_toc(html: str, color: str):
    """Retourne (nouveau_html, nb_sections) ou (None, 0) si rien à faire."""
    # 1) repérer tous les <div class="section"> SANS id, dans l'ordre
    positions = [m.start() for m in SECTION_OPEN_RE.finditer(html)]
    if not positions:
        return None, 0

    titles = []
    # on va reconstruire le html en ajoutant les id un par un
    new_html = html
    offset = 0
    for i, pos in enumerate(positions, start=1):
        pos += offset
        old_tag = '<div class="section">'
        new_tag = f'<div class="section" id="sec{i}">'
        new_html = new_html[:pos] + new_tag + new_html[pos + len(old_tag):]
        offset += len(new_tag) - len(old_tag)

        # extraire le titre du <h2> qui suit
        h2match = H2_RE.search(new_html, pos)
        title = h2match.group(1).strip() if h2match else f"Section {i}"
        # nettoyer d'éventuelles balises restantes (icônes etc.)
        title = re.sub(r'<[^>]+>', '', title).strip()
        titles.append(title)

    # 2) construire le bloc TOC
    li_items = "\n".join(
        f'                    <li><a href="#sec{i}"><span class="num">{i}.</span> {t}</a></li>'
        for i, t in enumerate(titles, start=1)
    )
    toc_block = (
        f'\n            <!-- ====== TABLE DES MATIÈRES (auto) ====== -->\n'
        f'            <div class="toc {color}">\n'
        f'                <h3><i class="fas fa-list"></i> Table des matières</h3>\n'
        f'                <ul>\n{li_items}\n                </ul>\n'
        f'            </div>\n'
    )

    # 3) insérer juste après le <h1 class="lesson-title"> (+ le <p> d'intro si présent)
    m = INTRO_P_RE.search(new_html)
    if not m:
        return None, 0
    insert_pos = m.end()
    new_html = new_html[:insert_pos] + toc_block + new_html[insert_pos:]

    return new_html, len(titles)


def ensure_toc_css(assets_css_dir: Path, dry_run: bool) -> bool:
    """Ajoute le CSS du .toc une seule fois dans lesson-common.css."""
    css_file = assets_css_dir / "lesson-common.css"
    if not css_file.exists():
        print(f"  ⚠ CSS introuvable: {css_file} (le style .toc doit être ajouté à la main)")
        return False
    content = css_file.read_text(encoding="utf-8")
    if TOC_CSS_MARKER in content:
        return False  # déjà présent
    if not dry_run:
        with css_file.open("a", encoding="utf-8") as f:
            f.write("\n" + TOC_CSS)
    print(f"  + CSS .toc ajouté à {css_file}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Ajoute la Table des matières aux parts qui n'en ont pas.")
    parser.add_argument("root", help="Dossier racine du site (ex: /storage/emulated/0/Web)")
    parser.add_argument("--dry-run", action="store_true", help="Analyse seulement, ne modifie rien")
    parser.add_argument("--no-backup", action="store_true", help="Ne pas créer de fichier .bak")
    args = parser.parse_args()

    root = Path(args.root)
    if not root.exists():
        print(f"Dossier introuvable: {root}")
        sys.exit(1)

    part_files = sorted(root.glob("content/*/lessons/*/model1/part*.html"))
    print(f"{len(part_files)} fichiers part*.html trouvés.\n")

    modified, skipped, errors = 0, 0, 0

    for fpath in part_files:
        try:
            html = fpath.read_text(encoding="utf-8")
        except Exception as e:
            print(f"✗ ERREUR lecture {fpath}: {e}")
            errors += 1
            continue

        if "Table des matières" in html:
            skipped += 1
            continue

        color = detect_color(fpath)
        new_html, n = build_toc(html, color)

        if new_html is None:
            print(f"⚠ Impossible de traiter (pas de <div class=\"section\"> détecté): {fpath}")
            errors += 1
            continue

        rel = fpath.relative_to(root)
        print(f"✓ {rel}  ->  {n} sections  [{color}]")

        if not args.dry_run:
            if not args.no_backup:
                bak = fpath.with_suffix(fpath.suffix + ".bak")
                if not bak.exists():
                    bak.write_text(html, encoding="utf-8")
            fpath.write_text(new_html, encoding="utf-8")

        modified += 1

    # ajouter le CSS (une seule fois par dossier assets/css rencontré)
    css_dirs = {p for p in root.glob("assets/css")}
    for css_dir in css_dirs:
        ensure_toc_css(css_dir, args.dry_run)

    print("\n" + "=" * 50)
    print(f"Modifiés   : {modified}")
    print(f"Déjà OK    : {skipped}")
    print(f"Erreurs    : {errors}")
    if args.dry_run:
        print("\n(mode --dry-run : aucun fichier n'a été modifié)")


if __name__ == "__main__":
    main()
