#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
fix_toc.py — يصلح ويوحد "Table des matières" فكل ملفات part*.html

كيدير 2 حوايج:
  A) الملفات اللي مازال ماعندهمش "Table des matières" -> كيزيدها
     (نفس المنطق ديال add_toc.py القديم: id="secN" لكل section + بناء اللائحة)
  B) الملفات اللي عندها ديجا Table des matières بصيغة مكسورة
     (class="toc red" / class="toc yellow" ديال add_toc.py القديم)
     -> كيصلح الكلاس لـ class="toc" وكيدرج التنسيق CSS الصحيح
        (نفس البطاقة الأصلية: بخلفية + حدود + border-radius) DIRECTEMENT
        جوا <style> ديال الصفحة نفسها (ماشي فملف خارجي)

اللون الحقيقي (مأخوذ من الصفحات الأصلية ديال المشروع):
    chimie   -> var(--gold-text)   (أصفر)
    physique -> #FF6B6B            (أحمر)
    math     -> #4ECDC4            (فيروزي/تركواز)

الصفحات اللي كانت ديجا صحيحة من الأصل (عندها .toc جوا <style> ديالها) -> ما كيمسهمش.
كيدير برضو تنظيف لملف lesson-common.css إلا كان فيه بقايا CSS ديال add_toc.py القديم.

الاستعمال:
    python3 fix_toc.py /storage/emulated/0/Web --dry-run
    python3 fix_toc.py /storage/emulated/0/Web
    python3 fix_toc.py /storage/emulated/0/Web --no-backup
"""

import re
import sys
import argparse
from pathlib import Path

ACCENT_BY_SUBJECT = {
    "chimie": "var(--gold-text)",
    "physique": "#FF6B6B",
    "math": "#4ECDC4",
}

TOC_CSS_TEMPLATE = """        .toc {{ background: var(--bg-card); border: 1px solid var(--border); border-radius: 8px; padding: 10px 14px; margin-bottom: 12px; }}
        .toc h3 {{ color:var(--gold-text); font-size: 13px; font-weight: 700; margin-bottom: 6px; }}
        .toc ul {{ list-style: none; padding: 0; }}
        .toc ul li {{ margin-bottom: 2px; }}
        .toc ul li a {{ color: var(--text-secondary); font-size: 12px; text-decoration: none; transition: color 0.2s; display: flex; align-items: center; gap: 6px; }}
        .toc ul li a:hover {{ color: {accent}; }}
        .toc ul li a .num {{ color: {accent}; font-weight: 700; font-size: 11px; min-width: 20px; }}
"""

OLD_SCRIPT_CSS_MARKER = "/* ====== Table des matières (auto-generated by add_toc.py) ====== */"

SECTION_OPEN_RE = re.compile(r'<div class="section">')
H2_RE = re.compile(r'<h2>\s*(?:<span class="num">\d+</span>\s*)?(.*?)\s*</h2>', re.S)
INTRO_P_RE = re.compile(r'(<h1 class="lesson-title">.*?</h1>\s*(?:<p[^>]*>.*?</p>\s*)?)', re.S)
STYLE_CLOSE_RE = re.compile(r'</style>')
BROKEN_CLASS_RE = re.compile(r'class="toc (red|yellow)"')


def detect_subject(path: Path) -> str:
    parts = {p.lower() for p in path.parts}
    for subj in ("chimie", "physique", "math"):
        if subj in parts:
            return subj
    return "math"


def inject_toc_css(html: str, accent: str) -> str:
    """Insère la règle .toc dans le PREMIER bloc <style> de la page (si absente)."""
    if re.search(r'\.toc\s*\{', html):
        return html  # déjà présent (page originale correcte) -> ne pas toucher
    m = STYLE_CLOSE_RE.search(html)
    if not m:
        return html  # pas de <style> trouvé (ne devrait pas arriver)
    css_block = TOC_CSS_TEMPLATE.format(accent=accent)
    pos = m.start()
    return html[:pos] + css_block + html[pos:]


def build_fresh_toc(html: str):
    """Cas A : page sans Table des matières du tout -> on la génère."""
    positions = [mm.start() for mm in SECTION_OPEN_RE.finditer(html)]
    if not positions:
        return None, 0

    titles = []
    new_html = html
    offset = 0
    for i, pos in enumerate(positions, start=1):
        pos += offset
        old_tag = '<div class="section">'
        new_tag = f'<div class="section" id="sec{i}">'
        new_html = new_html[:pos] + new_tag + new_html[pos + len(old_tag):]
        offset += len(new_tag) - len(old_tag)
        h2match = H2_RE.search(new_html, pos)
        title = h2match.group(1).strip() if h2match else f"Section {i}"
        title = re.sub(r'<[^>]+>', '', title).strip()
        titles.append(title)

    li_items = "\n".join(
        f'                    <li><a href="#sec{i}"><span class="num">{i}.</span> {t}</a></li>'
        for i, t in enumerate(titles, start=1)
    )
    toc_block = (
        f'\n            <!-- ====== TABLE DES MATIÈRES (auto) ====== -->\n'
        f'            <div class="toc">\n'
        f'                <h3><i class="fas fa-list"></i> Table des matières</h3>\n'
        f'                <ul>\n{li_items}\n                </ul>\n'
        f'            </div>\n'
    )
    m = INTRO_P_RE.search(new_html)
    if not m:
        return None, 0
    insert_pos = m.end()
    new_html = new_html[:insert_pos] + toc_block + new_html[insert_pos:]
    return new_html, len(titles)


def fix_broken_toc(html: str) -> str:
    """Cas B : classe cassée class="toc red"/"toc yellow" -> class="toc"."""
    return BROKEN_CLASS_RE.sub('class="toc"', html)


def clean_old_shared_css(assets_css_dir: Path, dry_run: bool) -> bool:
    css_file = assets_css_dir / "lesson-common.css"
    if not css_file.exists():
        return False
    content = css_file.read_text(encoding="utf-8")
    if OLD_SCRIPT_CSS_MARKER not in content:
        return False
    start = content.index(OLD_SCRIPT_CSS_MARKER)
    end_marker = "/* ====== fin Table des matières ====== */"
    end = content.find(end_marker)
    if end == -1:
        return False
    end += len(end_marker)
    new_content = content[:start].rstrip() + "\n" + content[end:].lstrip("\n")
    if not dry_run:
        css_file.write_text(new_content, encoding="utf-8")
    print(f"  🧹 CSS résiduel de l'ancien script retiré de {css_file}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Corrige et complète la Table des matières partout.")
    parser.add_argument("root", help="Dossier racine du site (ex: /storage/emulated/0/Web)")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--no-backup", action="store_true")
    args = parser.parse_args()

    root = Path(args.root)
    if not root.exists():
        print(f"Dossier introuvable: {root}")
        sys.exit(1)

    part_files = sorted(root.glob("content/*/lessons/*/model1/part*.html"))
    print(f"{len(part_files)} fichiers part*.html trouvés.\n")

    created, repaired, untouched, errors = 0, 0, 0, 0

    for fpath in part_files:
        try:
            html = fpath.read_text(encoding="utf-8")
        except Exception as e:
            print(f"✗ ERREUR lecture {fpath}: {e}")
            errors += 1
            continue

        subject = detect_subject(fpath)
        accent = ACCENT_BY_SUBJECT[subject]
        rel = fpath.relative_to(root)
        original = html

        if "Table des matières" not in html:
            # Cas A : rien du tout -> générer
            new_html, n = build_fresh_toc(html)
            if new_html is None:
                print(f"⚠ Impossible de traiter (pas de section détectée): {fpath}")
                errors += 1
                continue
            new_html = inject_toc_css(new_html, accent)
            print(f"+ CRÉÉ   {rel}  ({n} sections, {subject})")
            created += 1

        elif BROKEN_CLASS_RE.search(html):
            # Cas B : présent mais cassé (ancien script) -> réparer
            new_html = fix_broken_toc(html)
            new_html = inject_toc_css(new_html, accent)
            print(f"~ RÉPARÉ {rel}  ({subject})")
            repaired += 1

        else:
            # Cas C : déjà correct (page d'origine) -> ne rien faire
            untouched += 1
            continue

        if new_html != original and not args.dry_run:
            if not args.no_backup:
                bak = fpath.with_suffix(fpath.suffix + ".bak2")
                if not bak.exists():
                    bak.write_text(original, encoding="utf-8")
            fpath.write_text(new_html, encoding="utf-8")

    for css_dir in root.glob("assets/css"):
        clean_old_shared_css(css_dir, args.dry_run)

    print("\n" + "=" * 50)
    print(f"Nouvellement créés : {created}")
    print(f"Réparés (bug v1)   : {repaired}")
    print(f"Déjà corrects       : {untouched}")
    print(f"Erreurs             : {errors}")
    if args.dry_run:
        print("\n(mode --dry-run : aucun fichier n'a été modifié)")


if __name__ == "__main__":
    main()
